###### directory where results will be written
output_dir: ./results/

###### experiment & trial time limit in seconds (5 hours / 2 hours)
experiment_time_limit: 18000
trial_time_limit: 7200


###### number of trials for hyperparameter search & optimization
n_random_trials: 30
n_opt_trials: 0
hparam_seed: 0

###### GPU parameters
use_gpu: True
gpu_ids: [0]
data_parallel: True

###### Training parameters
batch_size: 128
val_batch_size: 256
early_stopping_rounds: 20
epochs: 100
logging_period: 100
